addSbtPlugin("org.scala-js"              % "sbt-scalajs"             % "1.18.2")
addSbtPlugin("com.github.sbt"            % "sbt-unidoc"              % "0.5.0")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"                 % "0.4.7")
addSbtPlugin("com.typesafe"              % "sbt-mima-plugin"         % "1.1.4")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"              % "5.10.0")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"            % "2.5.4")
addSbtPlugin("com.github.tkawachi"       % "sbt-doctest"             % "0.10.0")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"           % "2.3.1")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"            % "1.2.0")
addSbtPlugin("net.bzzt"                  % "sbt-reproducible-builds" % "0.32")
addSbtPlugin("org.typelevel"             % "sbt-tpolecat"            % "0.5.3")
addSbtPlugin("com.github.sbt"            % "sbt-dynver"              % "5.1.0")
addSbtPlugin("com.github.sbt"            % "sbt-git"                 % "2.1.0")
addSbtPlugin("org.xerial.sbt"            % "sbt-sonatype"            % "3.12.2")
addSbtPlugin("com.github.sbt"            % "sbt-pgp"                 % "2.3.1")

libraryDependencySchemes += "com.lihaoyi" %% "geny" % VersionScheme.Always